id: P16C164B6
initial_creation_type: ocr
source_metadata:
  volumes:
    90be755d494446d6923ea81a1b22f4ef:
      base_file: v107.txt
      image_group_id: I1PD95952
      title: དེ་ཁོ་ན་ཉིད་བསྡུས་པའི་དཀའ་འགྲེལ།
      total_pages: 1891
      volume_number: 107
vol2fn:
  v107: v107.txt
